name: Build PhanTomOS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toi uu khong gian o dia
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Kich hoat PhanTomOS Marble
        run: |
          echo "💀 Dang nap linh hon Dau Lau vao he thong..."
          echo "⏰ Kich hoat Dong ho Pixel Custom cho Marble..."
          echo "🚀 PhanTomOS dang chuan bi lo build..."
          sleep 10
          echo "----------------------------------------"
          echo "Trang thai: Da san sang de Sync Source!"
          echo "----------------------------------------"
