- name: Giai phong bo nho (Dọn dẹp ổ cứng)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          echo "🚀 Đã dọn dẹp xong! Hiện tại đang có:"
          df -h
